# SPDX-FileCopyrightText: 2026 Kevin Stenzel
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""initial schema

Revision ID: c85e6dacd792
Revises: 
Create Date: 2026-05-02 10:24:51.999212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85e6dacd792'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_agent_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_agent_keys_hashed_key'), 'monitor_agent_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_monitor_agent_keys_server_id'), 'monitor_agent_keys', ['server_id'], unique=True)
    op.create_table('monitor_alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('match_severity', sa.String(), nullable=True),
    sa.Column('match_server_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('channel_config', sa.String(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('template_def_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_alert_rules_template_id'), 'monitor_alert_rules', ['template_id'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('consecutive_fails', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('template_def_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_checks_server_id'), 'monitor_checks', ['server_id'], unique=False)
    op.create_index(op.f('ix_monitor_checks_template_id'), 'monitor_checks', ['template_id'], unique=False)
    op.create_table('monitor_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('check_definitions', sa.String(), nullable=False),
    sa.Column('alert_definitions', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_alert_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.String(), nullable=False),
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['monitor_alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_alert_log_alert_rule_id'), 'monitor_alert_log', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_monitor_alert_log_check_id'), 'monitor_alert_log', ['check_id'], unique=False)
    op.create_table('monitor_states',
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('since', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_table('monitor_template_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('server_hostname', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['monitor_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_template_assignments_server_id'), 'monitor_template_assignments', ['server_id'], unique=False)
    op.create_index(op.f('ix_monitor_template_assignments_template_id'), 'monitor_template_assignments', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_template_assignments_template_id'), table_name='monitor_template_assignments')
    op.drop_index(op.f('ix_monitor_template_assignments_server_id'), table_name='monitor_template_assignments')
    op.drop_table('monitor_template_assignments')
    op.drop_table('monitor_states')
    op.drop_index(op.f('ix_monitor_alert_log_check_id'), table_name='monitor_alert_log')
    op.drop_index(op.f('ix_monitor_alert_log_alert_rule_id'), table_name='monitor_alert_log')
    op.drop_table('monitor_alert_log')
    op.drop_table('monitor_templates')
    op.drop_index(op.f('ix_monitor_checks_template_id'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_server_id'), table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index(op.f('ix_monitor_alert_rules_template_id'), table_name='monitor_alert_rules')
    op.drop_table('monitor_alert_rules')
    op.drop_index(op.f('ix_monitor_agent_keys_server_id'), table_name='monitor_agent_keys')
    op.drop_index(op.f('ix_monitor_agent_keys_hashed_key'), table_name='monitor_agent_keys')
    op.drop_table('monitor_agent_keys')
    # ### end Alembic commands ###
